version: '2'

networks: 
  web:
    external: true

services:
  moarart:
    build: .
    restart: always
    ports: 
      - "3002:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.backend=moarart"
      - "traefik.frontend.rule=Host:moarart.mihiralve.com"
      - "traefik.port=3000"
    networks:
      - web